services:
  frontend:
    build: 
      context: "./frontend/."
      args:
        - SKELEARN_HOST=localhost
    ports:
      - "80:80"
      - "443:443"
  backend:
    build: "./backend/."
    environment:
      - "MONGO_URL=mongodb://mongo:27017"
  mongo:
    image: mongo