services:
  frontend:
    build: "./frontend/."
    ports:
      - "3000:80"
  backend:
    build: "./backend/."
    ports: 
      - "8080:8080"
    environment:
      - "MONGO_URL=mongodb://mongo:27017"
  mongo:
    image: mongo